swoop caboose configuration and handling
Element84/swoop-go pull request #4
Opened 2023-07-17 22:05 UTC by geomatician

Handling callback properties on/notOn, not when

Review config and make any snake_case keys camelCase

Load the swoop config into structs and can access the caboose-relevant portions within the caboose code where needed (argoCabooseRunner.wfDone())

**Parameter validation**

For each workflow’s callback’s parameters, validate that all of that callback’s handler’s required parameters are defined, and that no additional parameters are defined

Any missing required parameters is a parsing error

Any extra parameters not supported by the handler is a parsing error

Also consider how we can determine if a parameter is required or not

Differentiate between default: null and default being unset.

on/notOn, validating those values (error on conflict)

how to compare those to a workflow’s state: a function that takes a workflowProperties instance and compares its state value to those in on/notOn to return whether the callback should be run base on the workflow’s state, returning a bool

2023-07-17 22:12 UTC, geomatician commented
Regarding featureFilter (which was more of an investigation goal): there are already a couple packages that provide JsonPath support in Golang. Some of them are:
https://github.com/PaesslerAG/jsonpath (most popular one)
https://github.com/bhmj/jsonslice
https://github.com/ohler55/ojg
https://github.com/oliveagle/jsonpath)

An example of how to use the PaesslerAG/jsonpath package on a sample JSON file is provided in this attached file:

[jsonpath_test.zip](https://github.com/Element84/swoop-go/files/12074154/jsonpath_test.zip)

2023-07-18 18:57 UTC, jkeifer requested changes

2023-07-18 18:57 UTC, jkeifer commented on fixtures/swoop-config.yml
> +      workflow_name:
camelCase?

2023-07-18 18:57 UTC, jkeifer commented on fixtures/swoop-config.yml
> +    featureFilter: <jsonpath like workflow chaining filter>
We should probably come up with an actual expression for this, rather than the placeholder.

2023-07-18 18:57 UTC, jkeifer commented on pkg/caboose/argo.go
> +	if utils.Contains(cb.On, p.Status) && !utils.Contains(cb.NotOn, p.Status) {
It looks like you made `workflowProperties` and its `status` member public so you were able to import it in `parsing.go`. But because you are not doing that anymore, it seems like we should revert making those public.

2023-07-18 18:57 UTC, jkeifer commented on pkg/config/parsing.go
> +}
I think this should be removed.

2023-07-18 18:58 UTC, jkeifer commented on fixtures/swoop-config.yml
> +    featureFilter: <jsonpath like workflow chaining filter>
How about `"@.id =~ 'fake*' & @.properties.gsd <= 0"`?

2023-07-18 23:12 UTC, jkeifer approved these changes

2023-07-19 16:13 UTC, merged